name: hello world

# トリガー
on: pull_request

# ジョブごとに実行環境が構築されて、ジョブ内に定義されたステップが実行する
jobs:
  build:
    name: greeting
    runs-on: ubuntu-latest

    # コマンドやActionsなど実際の処理内容を記述する
    steps:
      - run: echo "Hello World"
